### PR TITLE
Implement hard cloning of data and vector

### PR DESCRIPTION
**Pull request by kylebarron**
For #8

### CODE REVIEW

**Comment by kylebarron** [comment]
image

this is hard to test because node doesn't have `ArrayBuffer.transfer` available, but checked manually in chrome and, originally the `geometryData` was shared (loaded from IPC) but after `hardClone`, `isShared` accurately said it was no longer shared, and even when I transfer one of the original buffers, the cloned data is still accessible

**Comment by trevorgerhardt** [comment]
Could try testing with the web-worker plugin: https://github.com/vitest-dev/vitest/tree/main/packages/web-worker. Not 100% sure it would suit your needs.

**Comment by kylebarron** [comment]
Cool! I didn't know about that.

It does say

> Transferring Buffer will not change its `byteLength`.

which means I don't think I'd be able to test what I want to test here. Maybe a better way to test this is just to check that the buffer backing the new `Data` instance is a different object

**Comment by trevorgerhardt** [comment]
Ah, yes, I now see that note. A "real" test might need automating running a browser like with Playwright.

Also, as you probably realize, this code doesn't appear GeoArrow specific. Could be useful to propose into the upstream Arrow-JS project?

(Note: I am casually investigating these tools and do not know the dynamics of the different projects.)

**Comment by kylebarron** [comment]
actually TIL node has a `structuredClone` method that correctly detaches arraybuffers: 
image

Yeah, it's not geoarrow specific, but contributing upstream to arrow-js has a lot of overhead, so I might as well incubate functionality here, so I can move more quickly, and maybe later integrate with arrowjs

**Pull request merged**
